### ISSUE TITLE
Improve Design

### ISSUE THREAD

**Issue by juanmanuelromeraferrio** [juanmanuelromeraferrio/calculadora-ganancias#3]
I need improve the basic design that has the site. If someone want to help me would be great!

**Comment by ReenaSingh07** [comment]
can i help you?

**Comment by juanmanuelromeraferrio** [comment]
Yes, feel free to change and improve the design.
Thanks!

**Comment by luisCislaghi** [comment]
Hi :)
I did some design improvements and it was made with love. Could you check my pull request?
![printscreen](https://user-images.githubusercontent.com/27792982/58557032-c42f9700-81f3-11e9-9463-ac159eb7b604.PNG)

**Comment by juanmanuelromeraferrio** [comment]
This Issues was closed with this PR -> https://github.com/juanmanuelromeraferrio/calculadora-ganancias/pull/4
